apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: provisioning-data
  description: Provisioning data from demo.redhat.com
  labels:
    ocp-apps-domain: apps.cluster-7zz2p.dynamic.redhatworkshops.io
    guid: 7zz2p
spec:
  type: service
  lifecycle: production
  owner: tssc
